### ISSUE TITLE
Fuck ZhiHu Mobile Style很好用，可以添加弹出窗体的修正么

### ISSUE THREAD

**Issue by pcloth** [ipcjs/bilibili-helper#323]
脚本问题：@ipcjs

## 描述
可以添加弹出窗体的修正么？
``` css
/* 弹出评论 */
.Modal-closeButton {
    position: static;
}
.Modal--fullPage {
    width: 100%;
}
```

然后再删除掉举报按钮，大部分时间都不会用到
``` js
function removeThankButton(node) {
        let count = 0
        node.querySelectorAll('button.ContentItem-action')
            .forEach(btn => {
                if (btn.innerText.includes('感谢')) {
                    btn.style.display = 'none'
                    count++
                }
                if (btn.innerText.includes('举报')) {
                    btn.style.display = 'none'
                    count++
                }
            })
        if (count > 0) {
            log(`remove: ${count}`)
        }
    }
```

感谢感谢，很好用！
