### ISSUE TITLE
Fuck ZhiHu Mobile Style 的弹窗不完全

### ISSUE THREAD

**Issue by pcloth** [ipcjs/bilibili-helper#342]
最后css改为这个似乎更合适一点。

```css
.Modal-closeButton {
    position: static;
    margin-left: auto;
    margin-right: auto;
}
.Modal {
    width: 100%;
}
```
